/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const EnvironmentId: core.serialization.Schema<serializers.EnvironmentId.Raw, FernIr.EnvironmentId>;
export declare namespace EnvironmentId {
    type Raw = string;
}
