/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const Environments: core.serialization.Schema<serializers.Environments.Raw, FernIr.Environments>;
export declare namespace Environments {
    type Raw = Environments.SingleBaseUrl | Environments.MultipleBaseUrls;
    interface SingleBaseUrl extends serializers.SingleBaseUrlEnvironments.Raw {
        type: "singleBaseUrl";
    }
    interface MultipleBaseUrls extends serializers.MultipleBaseUrlsEnvironments.Raw {
        type: "multipleBaseUrls";
    }
}
