/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const MultipleBaseUrlsEnvironment: core.serialization.ObjectSchema<serializers.MultipleBaseUrlsEnvironment.Raw, FernIr.MultipleBaseUrlsEnvironment>;
export declare namespace MultipleBaseUrlsEnvironment {
    interface Raw extends serializers.WithDocs.Raw {
        id: serializers.EnvironmentId.Raw;
        name: serializers.Name.Raw;
        urls: Record<serializers.EnvironmentBaseUrlId.Raw, serializers.EnvironmentUrl.Raw>;
    }
}
