/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const MultipleBaseUrlsEnvironments: core.serialization.ObjectSchema<serializers.MultipleBaseUrlsEnvironments.Raw, FernIr.MultipleBaseUrlsEnvironments>;
export declare namespace MultipleBaseUrlsEnvironments {
    interface Raw {
        baseUrls: serializers.EnvironmentBaseUrlWithId.Raw[];
        environments: serializers.MultipleBaseUrlsEnvironment.Raw[];
    }
}
