/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const SingleBaseUrlEnvironments: core.serialization.ObjectSchema<serializers.SingleBaseUrlEnvironments.Raw, FernIr.SingleBaseUrlEnvironments>;
export declare namespace SingleBaseUrlEnvironments {
    interface Raw {
        environments: serializers.SingleBaseUrlEnvironment.Raw[];
    }
}
