/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleQueryParameter: core.serialization.ObjectSchema<serializers.ExampleQueryParameter.Raw, FernIr.ExampleQueryParameter>;
export declare namespace ExampleQueryParameter {
    interface Raw {
        name: serializers.NameAndWireValue.Raw;
        value: serializers.ExampleTypeReference.Raw;
    }
}
