/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExamplePathParameter: core.serialization.ObjectSchema<serializers.ExamplePathParameter.Raw, FernIr.ExamplePathParameter>;
export declare namespace ExamplePathParameter {
    interface Raw {
        name: serializers.Name.Raw;
        value: serializers.ExampleTypeReference.Raw;
    }
}
