/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleEndpointCall: core.serialization.ObjectSchema<serializers.ExampleEndpointCall.Raw, FernIr.ExampleEndpointCall>;
export declare namespace ExampleEndpointCall {
    interface Raw extends serializers.WithDocs.Raw {
        name?: serializers.Name.Raw | null;
        url: string;
        rootPathParameters: serializers.ExamplePathParameter.Raw[];
        servicePathParameters: serializers.ExamplePathParameter.Raw[];
        endpointPathParameters: serializers.ExamplePathParameter.Raw[];
        serviceHeaders: serializers.ExampleHeader.Raw[];
        endpointHeaders: serializers.ExampleHeader.Raw[];
        queryParameters: serializers.ExampleQueryParameter.Raw[];
        request?: serializers.ExampleRequestBody.Raw | null;
        response: serializers.ExampleResponse.Raw;
    }
}
