/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleInlinedRequestBody: core.serialization.ObjectSchema<serializers.ExampleInlinedRequestBody.Raw, FernIr.ExampleInlinedRequestBody>;
export declare namespace ExampleInlinedRequestBody {
    interface Raw extends serializers.WithJsonExample.Raw {
        properties: serializers.ExampleInlinedRequestBodyProperty.Raw[];
    }
}
