/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleResponse: core.serialization.Schema<serializers.ExampleResponse.Raw, FernIr.ExampleResponse>;
export declare namespace ExampleResponse {
    type Raw = ExampleResponse.Ok | ExampleResponse.Error;
    interface Ok extends serializers.ExampleEndpointSuccessResponse.Raw {
        type: "ok";
    }
    interface Error extends serializers.ExampleEndpointErrorResponse.Raw {
        type: "error";
    }
}
