/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const FileDownloadResponse: core.serialization.ObjectSchema<serializers.FileDownloadResponse.Raw, FernIr.FileDownloadResponse>;
export declare namespace FileDownloadResponse {
    interface Raw extends serializers.WithDocs.Raw {
    }
}
