/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const FileUploadRequestProperty: core.serialization.Schema<serializers.FileUploadRequestProperty.Raw, FernIr.FileUploadRequestProperty>;
export declare namespace FileUploadRequestProperty {
    type Raw = FileUploadRequestProperty.File | FileUploadRequestProperty.BodyProperty;
    interface File extends serializers.FileProperty.Raw {
        type: "file";
    }
    interface BodyProperty extends serializers.InlinedRequestBodyProperty.Raw {
        type: "bodyProperty";
    }
}
