/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const FileUploadRequest: core.serialization.ObjectSchema<serializers.FileUploadRequest.Raw, FernIr.FileUploadRequest>;
export declare namespace FileUploadRequest {
    interface Raw {
        name: serializers.Name.Raw;
        properties: serializers.FileUploadRequestProperty.Raw[];
    }
}
