/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const HttpService: core.serialization.ObjectSchema<serializers.HttpService.Raw, FernIr.HttpService>;
export declare namespace HttpService {
    interface Raw {
        availability?: serializers.Availability.Raw | null;
        name: serializers.DeclaredServiceName.Raw;
        displayName?: string | null;
        basePath: serializers.HttpPath.Raw;
        endpoints: serializers.HttpEndpoint.Raw[];
        headers: serializers.HttpHeader.Raw[];
        pathParameters: serializers.PathParameter.Raw[];
    }
}
