/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const HttpMethod: core.serialization.Schema<serializers.HttpMethod.Raw, FernIr.HttpMethod>;
export declare namespace HttpMethod {
    type Raw = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
}
