/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const HttpEndpoint: core.serialization.ObjectSchema<serializers.HttpEndpoint.Raw, FernIr.HttpEndpoint>;
export declare namespace HttpEndpoint {
    interface Raw extends serializers.Declaration.Raw {
        id: serializers.EndpointId.Raw;
        name: serializers.EndpointName.Raw;
        displayName?: string | null;
        method: serializers.HttpMethod.Raw;
        headers: serializers.HttpHeader.Raw[];
        baseUrl?: serializers.EnvironmentBaseUrlId.Raw | null;
        path: serializers.HttpPath.Raw;
        fullPath: serializers.HttpPath.Raw;
        pathParameters: serializers.PathParameter.Raw[];
        allPathParameters: serializers.PathParameter.Raw[];
        queryParameters: serializers.QueryParameter.Raw[];
        requestBody?: serializers.HttpRequestBody.Raw | null;
        sdkRequest?: serializers.SdkRequest.Raw | null;
        response?: serializers.HttpResponse.Raw | null;
        errors: serializers.ResponseErrors.Raw;
        auth: boolean;
        idempotent: boolean;
        examples: serializers.ExampleEndpointCall.Raw[];
    }
}
