/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const HttpRequestBody: core.serialization.Schema<serializers.HttpRequestBody.Raw, FernIr.HttpRequestBody>;
export declare namespace HttpRequestBody {
    type Raw = HttpRequestBody.InlinedRequestBody | HttpRequestBody.Reference | HttpRequestBody.FileUpload | HttpRequestBody.Bytes;
    interface InlinedRequestBody extends serializers.InlinedRequestBody.Raw {
        type: "inlinedRequestBody";
    }
    interface Reference extends serializers.HttpRequestBodyReference.Raw {
        type: "reference";
    }
    interface FileUpload extends serializers.FileUploadRequest.Raw {
        type: "fileUpload";
    }
    interface Bytes extends serializers.BytesRequest.Raw {
        type: "bytes";
    }
}
