/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const HttpRequestBodyReference: core.serialization.ObjectSchema<serializers.HttpRequestBodyReference.Raw, FernIr.HttpRequestBodyReference>;
export declare namespace HttpRequestBodyReference {
    interface Raw extends serializers.WithDocs.Raw {
        requestBodyType: serializers.TypeReference.Raw;
        contentType?: string | null;
    }
}
