/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const PathParameterLocation: core.serialization.Schema<serializers.PathParameterLocation.Raw, FernIr.PathParameterLocation>;
export declare namespace PathParameterLocation {
    type Raw = "ROOT" | "SERVICE" | "ENDPOINT";
}
