/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ResponseError: core.serialization.ObjectSchema<serializers.ResponseError.Raw, FernIr.ResponseError>;
export declare namespace ResponseError {
    interface Raw extends serializers.WithDocs.Raw {
        error: serializers.DeclaredErrorName.Raw;
    }
}
