/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const SdkRequestBodyType: core.serialization.Schema<serializers.SdkRequestBodyType.Raw, FernIr.SdkRequestBodyType>;
export declare namespace SdkRequestBodyType {
    type Raw = SdkRequestBodyType.TypeReference | SdkRequestBodyType.Bytes;
    interface TypeReference extends serializers.HttpRequestBodyReference.Raw {
        type: "typeReference";
    }
    interface Bytes extends serializers.BytesRequest.Raw {
        type: "bytes";
    }
}
