/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const StreamingResponse: core.serialization.ObjectSchema<serializers.StreamingResponse.Raw, FernIr.StreamingResponse>;
export declare namespace StreamingResponse {
    interface Raw extends serializers.WithDocs.Raw {
        dataEventType: serializers.StreamingResponseChunkType.Raw;
        terminator?: string | null;
    }
}
