/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const VariableDeclaration: core.serialization.ObjectSchema<serializers.VariableDeclaration.Raw, FernIr.VariableDeclaration>;
export declare namespace VariableDeclaration {
    interface Raw extends serializers.WithDocs.Raw {
        id: serializers.VariableId.Raw;
        name: serializers.Name.Raw;
        type: serializers.TypeReference.Raw;
    }
}
