/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type AvailabilityStatus = "IN_DEVELOPMENT" | "PRE_RELEASE" | "GENERAL_AVAILABILITY" | "DEPRECATED";
export declare const AvailabilityStatus: {
    readonly InDevelopment: "IN_DEVELOPMENT";
    readonly PreRelease: "PRE_RELEASE";
    readonly GeneralAvailability: "GENERAL_AVAILABILITY";
    readonly Deprecated: "DEPRECATED";
    readonly _visit: <R>(value: AvailabilityStatus, visitor: AvailabilityStatus.Visitor<R>) => R;
};
export declare namespace AvailabilityStatus {
    interface Visitor<R> {
        inDevelopment: () => R;
        preRelease: () => R;
        generalAvailability: () => R;
        deprecated: () => R;
        _other: () => R;
    }
}
