/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const IntermediateRepresentation: core.serialization.ObjectSchema<serializers.IntermediateRepresentation.Raw, FernIr.IntermediateRepresentation>;
export declare namespace IntermediateRepresentation {
    interface Raw {
        apiName: serializers.Name.Raw;
        apiDisplayName?: string | null;
        apiDocs?: string | null;
        auth: serializers.ApiAuth.Raw;
        headers: serializers.HttpHeader.Raw[];
        idempotencyHeaders: serializers.HttpHeader.Raw[];
        types: Record<serializers.TypeId.Raw, serializers.TypeDeclaration.Raw>;
        services: Record<serializers.ServiceId.Raw, serializers.HttpService.Raw>;
        webhookGroups: Record<serializers.WebhookGroupId.Raw, serializers.WebhookGroup.Raw>;
        errors: Record<serializers.ErrorId.Raw, serializers.ErrorDeclaration.Raw>;
        subpackages: Record<serializers.SubpackageId.Raw, serializers.Subpackage.Raw>;
        rootPackage: serializers.Package.Raw;
        constants: serializers.Constants.Raw;
        environments?: serializers.EnvironmentsConfig.Raw | null;
        basePath?: serializers.HttpPath.Raw | null;
        pathParameters: serializers.PathParameter.Raw[];
        errorDiscriminationStrategy: serializers.ErrorDiscriminationStrategy.Raw;
        sdkConfig: serializers.SdkConfig.Raw;
        variables: serializers.VariableDeclaration.Raw[];
        serviceTypeReferenceInfo: serializers.ServiceTypeReferenceInfo.Raw;
    }
}
