/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const PackageNavigationConfig: core.serialization.ObjectSchema<serializers.PackageNavigationConfig.Raw, FernIr.PackageNavigationConfig>;
export declare namespace PackageNavigationConfig {
    interface Raw {
        pointsTo: serializers.SubpackageId.Raw;
    }
}
