"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeType = void 0;
exports.ShapeType = {
    Enum: "ENUM",
    Object: "OBJECT",
    Union: "UNION",
    UndiscriminatedUnion: "UNDISCRIMINATED_UNION",
    _visit: (value, visitor) => {
        switch (value) {
            case exports.ShapeType.Enum:
                return visitor.enum();
            case exports.ShapeType.Object:
                return visitor.object();
            case exports.ShapeType.Union:
                return visitor.union();
            case exports.ShapeType.UndiscriminatedUnion:
                return visitor.undiscriminatedUnion();
            default:
                return visitor._other();
        }
    },
};
