/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as FernIr from "../../..";
export declare type SingleUnionTypeProperties = FernIr.SingleUnionTypeProperties.SamePropertiesAsObject | FernIr.SingleUnionTypeProperties.SingleProperty | FernIr.SingleUnionTypeProperties.NoProperties;
export declare namespace SingleUnionTypeProperties {
    interface SamePropertiesAsObject extends FernIr.DeclaredTypeName, _Utils {
        propertiesType: "samePropertiesAsObject";
    }
    interface SingleProperty extends FernIr.SingleUnionTypeProperty, _Utils {
        propertiesType: "singleProperty";
    }
    interface NoProperties extends _Utils {
        propertiesType: "noProperties";
    }
    interface _Utils {
        _visit: <_Result>(visitor: FernIr.SingleUnionTypeProperties._Visitor<_Result>) => _Result;
    }
    interface _Visitor<_Result> {
        samePropertiesAsObject: (value: FernIr.DeclaredTypeName) => _Result;
        singleProperty: (value: FernIr.SingleUnionTypeProperty) => _Result;
        noProperties: () => _Result;
        _other: (value: {
            propertiesType: string;
        }) => _Result;
    }
}
export declare const SingleUnionTypeProperties: {
    readonly samePropertiesAsObject: (value: FernIr.DeclaredTypeName) => FernIr.SingleUnionTypeProperties.SamePropertiesAsObject;
    readonly singleProperty: (value: FernIr.SingleUnionTypeProperty) => FernIr.SingleUnionTypeProperties.SingleProperty;
    readonly noProperties: () => FernIr.SingleUnionTypeProperties.NoProperties;
    readonly _visit: <_Result>(value: FernIr.SingleUnionTypeProperties, visitor: FernIr.SingleUnionTypeProperties._Visitor<_Result>) => _Result;
};
