/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type AuthSchemesRequirement = "ALL" | "ANY";
export declare const AuthSchemesRequirement: {
    readonly All: "ALL";
    readonly Any: "ANY";
    readonly _visit: <R>(value: AuthSchemesRequirement, visitor: AuthSchemesRequirement.Visitor<R>) => R;
};
export declare namespace AuthSchemesRequirement {
    interface Visitor<R> {
        all: () => R;
        any: () => R;
        _other: () => R;
    }
}
