/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export declare const HttpMethod: {
    readonly Get: "GET";
    readonly Post: "POST";
    readonly Put: "PUT";
    readonly Patch: "PATCH";
    readonly Delete: "DELETE";
    readonly _visit: <R>(value: HttpMethod, visitor: HttpMethod.Visitor<R>) => R;
};
export declare namespace HttpMethod {
    interface Visitor<R> {
        get: () => R;
        post: () => R;
        put: () => R;
        patch: () => R;
        delete: () => R;
        _other: () => R;
    }
}
