"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpMethod = void 0;
exports.HttpMethod = {
    Get: "GET",
    Post: "POST",
    Put: "PUT",
    Patch: "PATCH",
    Delete: "DELETE",
    _visit: (value, visitor) => {
        switch (value) {
            case exports.HttpMethod.Get:
                return visitor.get();
            case exports.HttpMethod.Post:
                return visitor.post();
            case exports.HttpMethod.Put:
                return visitor.put();
            case exports.HttpMethod.Patch:
                return visitor.patch();
            case exports.HttpMethod.Delete:
                return visitor.delete();
            default:
                return visitor._other();
        }
    },
};
