/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as FernIr from "../../..";
export declare type HttpResponse = FernIr.HttpResponse.Json | FernIr.HttpResponse.FileDownload | FernIr.HttpResponse.Text | FernIr.HttpResponse.Streaming;
export declare namespace HttpResponse {
    interface Json extends _Utils {
        type: "json";
        value: FernIr.JsonResponse;
    }
    interface FileDownload extends FernIr.FileDownloadResponse, _Utils {
        type: "fileDownload";
    }
    interface Text extends FernIr.TextResponse, _Utils {
        type: "text";
    }
    interface Streaming extends FernIr.StreamingResponse, _Utils {
        type: "streaming";
    }
    interface _Utils {
        _visit: <_Result>(visitor: FernIr.HttpResponse._Visitor<_Result>) => _Result;
    }
    interface _Visitor<_Result> {
        json: (value: FernIr.JsonResponse) => _Result;
        fileDownload: (value: FernIr.FileDownloadResponse) => _Result;
        text: (value: FernIr.TextResponse) => _Result;
        streaming: (value: FernIr.StreamingResponse) => _Result;
        _other: (value: {
            type: string;
        }) => _Result;
    }
}
export declare const HttpResponse: {
    readonly json: (value: FernIr.JsonResponse) => FernIr.HttpResponse.Json;
    readonly fileDownload: (value: FernIr.FileDownloadResponse) => FernIr.HttpResponse.FileDownload;
    readonly text: (value: FernIr.TextResponse) => FernIr.HttpResponse.Text;
    readonly streaming: (value: FernIr.StreamingResponse) => FernIr.HttpResponse.Streaming;
    readonly _visit: <_Result>(value: FernIr.HttpResponse, visitor: FernIr.HttpResponse._Visitor<_Result>) => _Result;
};
