/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const DeclaredTypeName: core.serialization.ObjectSchema<serializers.DeclaredTypeName.Raw, FernIr.DeclaredTypeName>;
export declare namespace DeclaredTypeName {
    interface Raw {
        typeId: serializers.TypeId.Raw;
        fernFilepath: serializers.FernFilepath.Raw;
        name: serializers.Name.Raw;
    }
}
