/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const EnumTypeDeclaration: core.serialization.ObjectSchema<serializers.EnumTypeDeclaration.Raw, FernIr.EnumTypeDeclaration>;
export declare namespace EnumTypeDeclaration {
    interface Raw {
        values: serializers.EnumValue.Raw[];
    }
}
