/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const EnumValue: core.serialization.ObjectSchema<serializers.EnumValue.Raw, FernIr.EnumValue>;
export declare namespace EnumValue {
    interface Raw extends serializers.Declaration.Raw {
        name: serializers.NameAndWireValue.Raw;
    }
}
