/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleUndiscriminatedUnionType: core.serialization.ObjectSchema<serializers.ExampleUndiscriminatedUnionType.Raw, FernIr.ExampleUndiscriminatedUnionType>;
export declare namespace ExampleUndiscriminatedUnionType {
    interface Raw {
        index: number;
        singleUnionType: serializers.ExampleTypeReference.Raw;
    }
}
