/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleType: core.serialization.ObjectSchema<serializers.ExampleType.Raw, FernIr.ExampleType>;
export declare namespace ExampleType {
    interface Raw extends serializers.WithJsonExample.Raw, serializers.WithDocs.Raw {
        name?: serializers.Name.Raw | null;
        shape: serializers.ExampleTypeShape.Raw;
    }
}
