/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ExampleTypeReference: core.serialization.ObjectSchema<serializers.ExampleTypeReference.Raw, FernIr.ExampleTypeReference>;
export declare namespace ExampleTypeReference {
    interface Raw extends serializers.WithJsonExample.Raw {
        shape: serializers.ExampleTypeReferenceShape.Raw;
    }
}
