/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ResolvedNamedType: core.serialization.ObjectSchema<serializers.ResolvedNamedType.Raw, FernIr.ResolvedNamedType>;
export declare namespace ResolvedNamedType {
    interface Raw {
        name: serializers.DeclaredTypeName.Raw;
        shape: serializers.ShapeType.Raw;
    }
}
