/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const SingleUnionTypeProperty: core.serialization.ObjectSchema<serializers.SingleUnionTypeProperty.Raw, FernIr.SingleUnionTypeProperty>;
export declare namespace SingleUnionTypeProperty {
    interface Raw {
        name: serializers.NameAndWireValue.Raw;
        type: serializers.TypeReference.Raw;
    }
}
