/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const TypeDeclaration: core.serialization.ObjectSchema<serializers.TypeDeclaration.Raw, FernIr.TypeDeclaration>;
export declare namespace TypeDeclaration {
    interface Raw extends serializers.Declaration.Raw {
        name: serializers.DeclaredTypeName.Raw;
        shape: serializers.Type.Raw;
        examples: serializers.ExampleType.Raw[];
        referencedTypes: serializers.TypeId.Raw[];
    }
}
