/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const Type: core.serialization.Schema<serializers.Type.Raw, FernIr.Type>;
export declare namespace Type {
    type Raw = Type.Alias | Type.Enum | Type.Object | Type.Union | Type.UndiscriminatedUnion;
    interface Alias extends serializers.AliasTypeDeclaration.Raw {
        _type: "alias";
    }
    interface Enum extends serializers.EnumTypeDeclaration.Raw {
        _type: "enum";
    }
    interface Object extends serializers.ObjectTypeDeclaration.Raw {
        _type: "object";
    }
    interface Union extends serializers.UnionTypeDeclaration.Raw {
        _type: "union";
    }
    interface UndiscriminatedUnion extends serializers.UndiscriminatedUnionTypeDeclaration.Raw {
        _type: "undiscriminatedUnion";
    }
}
