/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const DeclaredErrorName: core.serialization.ObjectSchema<serializers.DeclaredErrorName.Raw, FernIr.DeclaredErrorName>;
export declare namespace DeclaredErrorName {
    interface Raw {
        errorId: serializers.ErrorId.Raw;
        fernFilepath: serializers.FernFilepath.Raw;
        name: serializers.Name.Raw;
    }
}
