/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ErrorDeclaration: core.serialization.ObjectSchema<serializers.ErrorDeclaration.Raw, FernIr.ErrorDeclaration>;
export declare namespace ErrorDeclaration {
    interface Raw extends serializers.WithDocs.Raw {
        name: serializers.DeclaredErrorName.Raw;
        discriminantValue: serializers.NameAndWireValue.Raw;
        type?: serializers.TypeReference.Raw | null;
        statusCode: number;
    }
}
