"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FernIrTimeoutError = void 0;
class FernIrTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, FernIrTimeoutError.prototype);
    }
}
exports.FernIrTimeoutError = FernIrTimeoutError;
