/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const ErrorId: core.serialization.Schema<serializers.ErrorId.Raw, FernIr.ErrorId>;
export declare namespace ErrorId {
    type Raw = string;
}
