/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const EscapedString: core.serialization.ObjectSchema<serializers.EscapedString.Raw, FernIr.EscapedString>;
export declare namespace EscapedString {
    interface Raw {
        original: string;
    }
}
