/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const TypeId: core.serialization.Schema<serializers.TypeId.Raw, FernIr.TypeId>;
export declare namespace TypeId {
    type Raw = string;
}
