/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const WithJsonExample: core.serialization.ObjectSchema<serializers.WithJsonExample.Raw, FernIr.WithJsonExample>;
export declare namespace WithJsonExample {
    interface Raw {
        jsonExample?: unknown;
    }
}
