/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const AuthScheme: core.serialization.Schema<serializers.AuthScheme.Raw, FernIr.AuthScheme>;
export declare namespace AuthScheme {
    type Raw = AuthScheme.Bearer | AuthScheme.Basic | AuthScheme.Header;
    interface Bearer extends serializers.BearerAuthScheme.Raw {
        _type: "bearer";
    }
    interface Basic extends serializers.BasicAuthScheme.Raw {
        _type: "basic";
    }
    interface Header extends serializers.HeaderAuthScheme.Raw {
        _type: "header";
    }
}
