/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const BearerAuthScheme: core.serialization.ObjectSchema<serializers.BearerAuthScheme.Raw, FernIr.BearerAuthScheme>;
export declare namespace BearerAuthScheme {
    interface Raw extends serializers.WithDocs.Raw {
        token: serializers.Name.Raw;
        tokenEnvVar?: serializers.EnvironmentVariable.Raw | null;
    }
}
