/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const EnvironmentVariable: core.serialization.Schema<serializers.EnvironmentVariable.Raw, FernIr.EnvironmentVariable>;
export declare namespace EnvironmentVariable {
    type Raw = string;
}
