/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const InlinedWebhookPayload: core.serialization.ObjectSchema<serializers.InlinedWebhookPayload.Raw, FernIr.InlinedWebhookPayload>;
export declare namespace InlinedWebhookPayload {
    interface Raw {
        name: serializers.Name.Raw;
        extends: serializers.DeclaredTypeName.Raw[];
        properties: serializers.InlinedWebhookPayloadProperty.Raw[];
    }
}
