/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const InlinedWebhookPayloadProperty: core.serialization.ObjectSchema<serializers.InlinedWebhookPayloadProperty.Raw, FernIr.InlinedWebhookPayloadProperty>;
export declare namespace InlinedWebhookPayloadProperty {
    interface Raw extends serializers.WithDocs.Raw {
        name: serializers.NameAndWireValue.Raw;
        valueType: serializers.TypeReference.Raw;
    }
}
