/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const WebhookGroup: core.serialization.Schema<serializers.WebhookGroup.Raw, FernIr.WebhookGroup>;
export declare namespace WebhookGroup {
    type Raw = serializers.Webhook.Raw[];
}
