/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const Webhook: core.serialization.ObjectSchema<serializers.Webhook.Raw, FernIr.Webhook>;
export declare namespace Webhook {
    interface Raw extends serializers.Declaration.Raw {
        name: serializers.WebhookName.Raw;
        displayName?: string | null;
        method: serializers.WebhookHttpMethod.Raw;
        headers: serializers.HttpHeader.Raw[];
        payload: serializers.WebhookPayload.Raw;
    }
}
