/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as FernIr from "../../../../api";
import * as core from "../../../../core";
export declare const WebhookPayload: core.serialization.Schema<serializers.WebhookPayload.Raw, FernIr.WebhookPayload>;
export declare namespace WebhookPayload {
    type Raw = WebhookPayload.InlinedPayload | WebhookPayload.Reference;
    interface InlinedPayload extends serializers.InlinedWebhookPayload.Raw {
        type: "inlinedPayload";
    }
    interface Reference extends serializers.WebhookPayloadReference.Raw {
        type: "reference";
    }
}
